-- QUICK DUMMY DATA SCRIPT
-- Run this in Supabase SQL Editor to populate your database with test data
-- Make sure to run the main migration first!

-- ============================================
-- STEP 1: Insert Dummy Employees
-- ============================================

INSERT INTO employees (id, name, email, role) VALUES
  ('11111111-1111-1111-1111-111111111111', 'John Doe', 'john.doe@example.com', 'employee'),
  ('22222222-2222-2222-2222-222222222222', 'Jane Smith', 'jane.smith@example.com', 'employee'),
  ('33333333-3333-3333-3333-333333333333', 'Bob Johnson', 'bob.johnson@example.com', 'employee'),
  ('44444444-4444-4444-4444-444444444444', 'Alice Williams', 'alice.williams@example.com', 'admin'),
  ('55555555-5555-5555-5555-555555555555', 'Charlie Brown', 'charlie.brown@example.com', 'employee')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  role = EXCLUDED.role;

-- ============================================
-- STEP 2: Insert Sample Attendance Logs
-- ============================================

-- Today's logs for John Doe (full day, on time)
INSERT INTO attendance_logs (employee_id, action_type, timestamp) VALUES
  ('11111111-1111-1111-1111-111111111111', 'start_work', CURRENT_DATE + INTERVAL '8 hours'),
  ('11111111-1111-1111-1111-111111111111', 'start_break', CURRENT_DATE + INTERVAL '12 hours'),
  ('11111111-1111-1111-1111-111111111111', 'end_break', CURRENT_DATE + INTERVAL '12 hours 30 minutes'),
  ('11111111-1111-1111-1111-111111111111', 'end_work', CURRENT_DATE + INTERVAL '17 hours')
ON CONFLICT DO NOTHING;

-- Yesterday's logs for John (late arrival)
INSERT INTO attendance_logs (employee_id, action_type, timestamp) VALUES
  ('11111111-1111-1111-1111-111111111111', 'start_work', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '9 hours 15 minutes'),
  ('11111111-1111-1111-1111-111111111111', 'start_break', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '13 hours'),
  ('11111111-1111-1111-1111-111111111111', 'end_break', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '13 hours 30 minutes'),
  ('11111111-1111-1111-1111-111111111111', 'end_work', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '17 hours 30 minutes')
ON CONFLICT DO NOTHING;

-- Today's logs for Jane (under hours)
INSERT INTO attendance_logs (employee_id, action_type, timestamp) VALUES
  ('22222222-2222-2222-2222-222222222222', 'start_work', CURRENT_DATE + INTERVAL '8 hours 30 minutes'),
  ('22222222-2222-2222-2222-222222222222', 'start_break', CURRENT_DATE + INTERVAL '12 hours 15 minutes'),
  ('22222222-2222-2222-2222-222222222222', 'end_break', CURRENT_DATE + INTERVAL '12 hours 45 minutes'),
  ('22222222-2222-2222-2222-222222222222', 'end_work', CURRENT_DATE + INTERVAL '16 hours 45 minutes')
ON CONFLICT DO NOTHING;

-- Today's logs for Bob (currently working, hasn't ended)
INSERT INTO attendance_logs (employee_id, action_type, timestamp) VALUES
  ('33333333-3333-3333-3333-333333333333', 'start_work', CURRENT_DATE + INTERVAL '8 hours'),
  ('33333333-3333-3333-3333-333333333333', 'start_break', CURRENT_DATE + INTERVAL '12 hours'),
  ('33333333-3333-3333-3333-333333333333', 'end_break', CURRENT_DATE + INTERVAL '12 hours 30 minutes')
ON CONFLICT DO NOTHING;

-- Last 7 days of logs for John (for reports)
DO $$
DECLARE
  i INTEGER;
  log_date DATE;
  john_id UUID := '11111111-1111-1111-1111-111111111111';
BEGIN
  FOR i IN 0..6 LOOP
    log_date := CURRENT_DATE - (i || ' days')::INTERVAL;
    
    INSERT INTO attendance_logs (employee_id, action_type, timestamp) VALUES
      (john_id, 'start_work', log_date + INTERVAL '8 hours'),
      (john_id, 'start_break', log_date + INTERVAL '12 hours'),
      (john_id, 'end_break', log_date + INTERVAL '12 hours 30 minutes'),
      (john_id, 'end_work', log_date + INTERVAL '17 hours')
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

-- ============================================
-- STEP 3: Verify Data
-- ============================================

-- Check employees
SELECT 'Employees' as table_name, COUNT(*) as count FROM employees;

-- Check attendance logs
SELECT 'Attendance Logs' as table_name, COUNT(*) as count FROM attendance_logs;

-- Check daily summaries (should be auto-generated by triggers)
SELECT 'Daily Summaries' as table_name, COUNT(*) as count FROM daily_summary;

-- View sample data
SELECT 
  e.name,
  e.role,
  COUNT(al.id) as total_logs,
  MAX(al.timestamp) as last_activity
FROM employees e
LEFT JOIN attendance_logs al ON e.id = al.employee_id
GROUP BY e.id, e.name, e.role
ORDER BY e.name;

